date = "2026-10-04"
row = "W64"
pin = "REL_18_6"
commit = "724edf9bde9d356724ad384a2e196edc3c9f80f7"
config = "minimal"
system = "meson"
level = "-O2"
compiler = "rucc 0.19.0"
host = "runnervmdlhio"
built = true
failing = ["world/xid_wraparound/002_limits"]

[counts]
failed = 1
passed = 911
